import { Meal, Restaurant, UserProfile, Order } from '../../types';

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest_thai',
    name: 'Thai Orchid Street',
    cuisine: 'Thai',
    rating: 4.8,
    deliveryTimeMinutes: 25,
    deliveryFee: 2.99,
    minimumOrder: 10,
    active: true,
    address: '142 Market St, Central',
  },
  {
    id: 'rest_tokyo',
    name: 'Tokyo Bento Co.',
    cuisine: 'Japanese',
    rating: 4.9,
    deliveryTimeMinutes: 20,
    deliveryFee: 1.99,
    minimumOrder: 12,
    active: true,
    address: '88 Bushnell Ave, Uptown',
  },
  {
    id: 'rest_verde',
    name: 'Verde Kitchen & Bowls',
    cuisine: 'Mediterranean',
    rating: 4.7,
    deliveryTimeMinutes: 30,
    deliveryFee: 2.49,
    minimumOrder: 10,
    active: true,
    address: '210 Green St, Arts District',
  },
  {
    id: 'rest_fuego',
    name: 'El Fuego Taqueria',
    cuisine: 'Mexican',
    rating: 4.6,
    deliveryTimeMinutes: 25,
    deliveryFee: 1.99,
    minimumOrder: 10,
    active: true,
    address: '55 Mission Blvd, Southside',
  },
  {
    id: 'rest_roma',
    name: 'Roma Cucina',
    cuisine: 'Italian',
    rating: 4.7,
    deliveryTimeMinutes: 35,
    deliveryFee: 3.49,
    minimumOrder: 15,
    active: true,
    address: '304 Columbus Ave, North Beach',
  },
  {
    id: 'rest_seoul',
    name: 'Seoul Spice House',
    cuisine: 'Korean',
    rating: 4.8,
    deliveryTimeMinutes: 25,
    deliveryFee: 2.49,
    minimumOrder: 12,
    active: true,
    address: '714 Geary St, Downtown',
  },
  {
    id: 'rest_gulati',
    name: "Gulati's Indian Kitchen",
    cuisine: 'Indian',
    rating: 4.8,
    deliveryTimeMinutes: 25,
    deliveryFee: 1.99,
    minimumOrder: 10,
    active: true,
    address: 'Curtin Hub, Building 104',
  },
  {
    id: 'rest_suya',
    name: 'Suya King African Kitchen',
    cuisine: 'African',
    rating: 4.9,
    deliveryTimeMinutes: 30,
    deliveryFee: 2.49,
    minimumOrder: 10,
    active: true,
    address: 'Bentley Plaza, Shop 12',
  },
  {
    id: 'rest_dragon',
    name: 'Dragon Wok Box',
    cuisine: 'Chinese',
    rating: 4.6,
    deliveryTimeMinutes: 20,
    deliveryFee: 1.99,
    minimumOrder: 10,
    active: true,
    address: 'Curtin Guild Courtyard',
  },
  {
    id: 'rest_kopitiam',
    name: 'Kopitiam Nanyang Flavours',
    cuisine: 'Malaysian',
    rating: 4.8,
    deliveryTimeMinutes: 25,
    deliveryFee: 2.00,
    minimumOrder: 10,
    active: true,
    address: 'Victoria Park Hub, 88 Albany Hwy',
  },
];

export const MOCK_MEALS: Meal[] = [
  // Signature Healthy Reference Meals (from Drop AI Reference Mockup Panels 3 & 4)
  {
    id: 'meal_grilled_chicken_quinoa_bowl',
    name: 'Grilled Chicken Quinoa Bowl',
    description: 'Tender grilled chicken breast over fluffy organic quinoa, roasted sweet potatoes, and steamed greens.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 12.00,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mediterranean',
    category: 'main',
    dietaryTags: ['High Protein', 'Low Sodium', 'gluten-free', 'healthy'],
    ingredients: ['grilled chicken', 'quinoa', 'sweet potato', 'kale', 'olive oil'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 480,
    proteinGrams: 42,
  },
  {
    id: 'meal_salmon_brown_rice',
    name: 'Salmon & Brown Rice',
    description: 'Pan-seared Atlantic salmon fillet with steamed brown rice, edamame, and sesame ginger dressing.',
    restaurantId: 'rest_tokyo',
    restaurantName: 'Tokyo Bento Co.',
    price: 13.50,
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Japanese',
    category: 'main',
    dietaryTags: ['Heart Healthy', 'Gluten Free', 'gluten-free', 'healthy'],
    ingredients: ['salmon fillet', 'brown rice', 'edamame', 'sesame', 'ginger'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 520,
    proteinGrams: 38,
  },
  {
    id: 'meal_beetroot_tofu_salad',
    name: 'Beetroot & Tofu Salad',
    description: 'Crispy organic tofu cubes, roasted golden beetroot, mixed baby greens, and toasted sunflower seeds.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 11.50,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mediterranean',
    category: 'main',
    dietaryTags: ['Vegan', 'High Fibre', 'vegan', 'vegetarian', 'gluten-free', 'healthy'],
    ingredients: ['tofu', 'beetroot', 'baby greens', 'sunflower seeds', 'citrus dressing'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 380,
    proteinGrams: 22,
  },
  {
    id: 'meal_thai_basil_chicken',
    name: 'Thai Basil Chicken',
    description: 'Minced chicken stir-fried with fragrant holy basil, garlic, and fresh chilies, served with jasmine rice.',
    restaurantId: 'rest_thai',
    restaurantName: 'Thai Orchid Street',
    price: 13.00,
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Thai',
    category: 'main',
    dietaryTags: ['High Protein', 'Low Calorie', 'dairy-free', 'healthy'],
    ingredients: ['chicken mince', 'holy basil', 'garlic', 'chili', 'jasmine rice'],
    spicyLevel: 2,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 460,
    proteinGrams: 36,
  },
  {
    id: 'meal_lentil_veggie_curry',
    name: 'Lentil & Veggie Curry',
    description: 'Slow-simmered yellow lentils with seasonal garden vegetables, cumin, turmeric, and steamed basmati rice.',
    restaurantId: 'rest_gulati',
    restaurantName: "Gulati's Indian Kitchen",
    price: 12.00,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Indian',
    category: 'main',
    dietaryTags: ['Vegan', 'High Fibre', 'vegan', 'vegetarian', 'gluten-free', 'healthy'],
    ingredients: ['yellow lentils', 'spinach', 'carrots', 'turmeric', 'basmati rice'],
    spicyLevel: 1,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 420,
    proteinGrams: 20,
  },
  // Signature Daily Drop Meals (from Drop AI Specification)
  {
    id: 'meal_hyderabadi_chicken_biryani',
    name: 'Chicken Biryani (Indian)',
    description: 'Dum-cooked aromatic basmati rice layered with spiced marinated tender chicken, saffron, and fried onions.',
    restaurantId: 'rest_gulati',
    restaurantName: "Gulati's Indian Kitchen",
    price: 12.00,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Indian',
    category: 'main',
    dietaryTags: ['halal', 'gluten-free', 'high-protein'],
    ingredients: ['chicken', 'basmati rice', 'saffron', 'onion', 'yoghurt', 'cardamom'],
    spicyLevel: 2,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 680,
    proteinGrams: 42,
  },
  {
    id: 'meal_west_african_jollof_chicken',
    name: 'Jollof Chicken (African)',
    description: 'West African fire-roasted tomato and pepper rice served with succulent spiced roast chicken and sweet fried plantain.',
    restaurantId: 'rest_suya',
    restaurantName: 'Suya King African Kitchen',
    price: 12.00,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    cuisine: 'African',
    category: 'main',
    dietaryTags: ['halal', 'dairy-free', 'high-protein', 'gluten-free'],
    ingredients: ['chicken', 'jollof rice', 'habanero', 'red bell pepper', 'tomatoes', 'plantain'],
    spicyLevel: 3,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 650,
    proteinGrams: 40,
  },
  {
    id: 'meal_butter_chicken_roti',
    name: 'Butter Chicken with Garlic Roti',
    description: 'Tender marinated tandoori chicken simmered in rich velvety butter tomato makhani sauce with warm garlic roti.',
    restaurantId: 'rest_gulati',
    restaurantName: "Gulati's Indian Kitchen",
    price: 14.00,
    imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Indian',
    category: 'main',
    dietaryTags: ['halal'],
    ingredients: ['chicken', 'makhani sauce', 'butter', 'cream', 'garlic roti'],
    spicyLevel: 1,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 710,
    proteinGrams: 36,
  },
  {
    id: 'meal_beef_rendang_bowl',
    name: 'Beef Rendang Bowl',
    description: 'Tender slow-simmered beef caramelized in rich toasted coconut flakes, lemongrass, kaffir lime, and fragrant jasmine rice.',
    restaurantId: 'rest_kopitiam',
    restaurantName: 'Kopitiam Nanyang Flavours',
    price: 13.00,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Malaysian',
    category: 'main',
    dietaryTags: ['halal', 'dairy-free', 'gluten-free'],
    ingredients: ['beef chuck', 'coconut flakes', 'lemongrass', 'galangal', 'jasmine rice'],
    spicyLevel: 3,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 640,
    proteinGrams: 38,
  },
  {
    id: 'meal_slow_cooked_beef_lasagne',
    name: 'Beef Lasagne',
    description: 'Layered artisan pasta sheets baked with 6-hour slow-cooked Angus beef bolognese, creamy bechamel, and melted mozzarella.',
    restaurantId: 'rest_roma',
    restaurantName: 'Roma Cucina',
    price: 14.00,
    imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Italian',
    category: 'main',
    dietaryTags: ['high-protein'],
    ingredients: ['beef', 'pasta sheets', 'bechamel', 'mozzarella', 'tomato sauce'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['dinner'],
    active: true,
    calories: 690,
    proteinGrams: 35,
  },
  {
    id: 'meal_chicken_caesar_salad',
    name: 'Chicken Caesar Salad',
    description: 'Grilled herb chicken breast over crisp romaine hearts, aged shaved parmesan, poached egg, and light dressing.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 11.00,
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mediterranean',
    category: 'main',
    dietaryTags: ['high-protein', 'gluten-free', 'weight-management'],
    ingredients: ['chicken', 'romaine', 'parmesan', 'egg', 'caesar dressing'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 450,
    proteinGrams: 42,
  },
  {
    id: 'meal_penne_pasta_chicken',
    name: 'Penne Pasta with Chicken',
    description: 'Bronze-extruded penne pasta tossed with fresh sweet Genovese basil pesto and juicy seared chicken breast.',
    restaurantId: 'rest_roma',
    restaurantName: 'Roma Cucina',
    price: 13.00,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281781?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Italian',
    category: 'main',
    dietaryTags: ['high-protein'],
    ingredients: ['chicken', 'penne pasta', 'basil pesto', 'parmesan'],
    spicyLevel: 0,
    availableDays: ['monday', 'wednesday', 'thursday', 'friday', 'saturday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 610,
    proteinGrams: 37,
  },
  {
    id: 'meal_malaysian_mee_goreng',
    name: 'Chicken Mee Goreng',
    description: 'Wok-tossed noodles with chicken, crispy tofu, bean sprouts, sweet soy, and spicy sambal.',
    restaurantId: 'rest_kopitiam',
    restaurantName: 'Kopitiam Nanyang Flavours',
    price: 12.00,
    imageUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Malaysian',
    category: 'main',
    dietaryTags: ['halal', 'dairy-free'],
    ingredients: ['chicken', 'yellow noodles', 'sambal', 'tofu', 'egg', 'cabbage'],
    spicyLevel: 3,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 590,
    proteinGrams: 32,
  },
  {
    id: 'meal_halloumi_grain_bowl',
    name: 'Halloumi Grain Bowl',
    description: 'Pan-seared Cypriot halloumi cheese over ancient tricolor quinoa, roasted beets, baby spinach, and pomegranate glaze.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 13.00,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mediterranean',
    category: 'main',
    dietaryTags: ['vegetarian', 'high-fibre', 'gut-friendly', 'weight-management'],
    ingredients: ['halloumi', 'quinoa', 'beets', 'spinach', 'pomegranate'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 520,
    proteinGrams: 24,
  },

  // Mains
  {
    id: 'meal_grilled_chicken_quinoa_bowl',
    name: 'Grilled Chicken Quinoa Bowl',
    description: 'Tender grilled chicken breast over organic tri-color quinoa, Persian cucumbers, avocado, and herb lemon vinaigrette.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 12.00,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mediterranean',
    category: 'main',
    dietaryTags: ['high-protein', 'low-sodium', 'healthy', 'weight-management', 'high-fibre', 'gut-friendly'],
    ingredients: ['grilled chicken', 'quinoa', 'cucumber', 'avocado', 'lemon herb vinaigrette'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 520,
    proteinGrams: 42,
  },
  {
    id: 'meal_thai_basil_chicken',
    name: 'Thai Basil Chicken',
    description: 'Wok-seared minced chicken with bird’s eye chili, holy basil, garlic, and jasmine rice topped with crispy fried egg.',
    restaurantId: 'rest_thai',
    restaurantName: 'Thai Orchid Street',
    price: 13.00,
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Thai',
    category: 'main',
    dietaryTags: ['diabetes-friendly', 'gluten-free', 'high-protein'],
    ingredients: ['chicken', 'thai basil', 'bird eye chili', 'garlic', 'jasmine rice', 'soy sauce', 'egg'],
    spicyLevel: 2,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 640,
    proteinGrams: 38,
  },
  {
    id: 'meal_spicy_katsu_chicken',
    name: 'Spicy Chicken Katsu Curry',
    description: 'Crispy panko chicken cutlet served with aromatic house Japanese curry, steamed koshihikari rice, and pickled daikon.',
    restaurantId: 'rest_tokyo',
    restaurantName: 'Tokyo Bento Co.',
    price: 14.50,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Japanese',
    category: 'main',
    dietaryTags: ['dairy-free', 'high-protein'],
    ingredients: ['chicken', 'panko', 'japanese curry', 'rice', 'onions', 'carrots', 'pickles'],
    spicyLevel: 2,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 720,
    proteinGrams: 42,
  },
  {
    id: 'meal_teriyaki_chicken_bowl',
    name: 'Glazed Chicken Teriyaki Bowl',
    description: 'Flame-grilled chicken thigh glazed with handcrafted sweet mirin teriyaki, sesame broccoli, and fluffy brown rice.',
    restaurantId: 'rest_tokyo',
    restaurantName: 'Tokyo Bento Co.',
    price: 13.50,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Japanese',
    category: 'main',
    dietaryTags: ['dairy-free', 'high-protein'],
    ingredients: ['chicken', 'teriyaki sauce', 'broccoli', 'brown rice', 'sesame'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 590,
    proteinGrams: 39,
  },
  {
    id: 'meal_chipotle_chicken_bowl',
    name: 'Chipotle Lime Chicken Bowl',
    description: 'Citrus-marinated roasted chicken breast, spiced black beans, charred corn pico, cilantro-lime brown rice.',
    restaurantId: 'rest_fuego',
    restaurantName: 'El Fuego Taqueria',
    price: 12.50,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mexican',
    category: 'main',
    dietaryTags: ['gluten-free', 'high-protein', 'dairy-free'],
    ingredients: ['chicken', 'chipotle', 'black beans', 'corn', 'brown rice', 'cilantro', 'lime'],
    spicyLevel: 1,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 560,
    proteinGrams: 44,
  },
  {
    id: 'meal_korean_spicy_chicken',
    name: 'Gochujang Fire Chicken (Buldak)',
    description: 'Fiery sweet gochujang glazed chicken bites served over purple multigrain rice with scallions and sesame.',
    restaurantId: 'rest_seoul',
    restaurantName: 'Seoul Spice House',
    price: 14.00,
    imageUrl: 'https://images.unsplash.com/photo-1527477321055-436158a257a5?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Korean',
    category: 'main',
    dietaryTags: ['high-protein', 'dairy-free'],
    ingredients: ['chicken', 'gochujang', 'garlic', 'purple rice', 'scallions', 'sesame oil'],
    spicyLevel: 3,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    availableSlots: ['dinner'],
    active: true,
    calories: 680,
    proteinGrams: 41,
  },
  {
    id: 'meal_falafel_power_bowl',
    name: 'Crispy Falafel & Tahini Bowl',
    description: 'Golden herbed chickpea falafel, velvety garlic hummus, Persian cucumber salad, kalamata olives, and warm sumac flatbread.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 12.00,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mediterranean',
    category: 'main',
    dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'high-fibre', 'gut-friendly', 'weight-management'],
    ingredients: ['chickpeas', 'herbs', 'tahini', 'hummus', 'cucumber', 'tomatoes', 'olives', 'pita'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 510,
    proteinGrams: 20,
  },
  {
    id: 'meal_spicy_tofu_pad_thai',
    name: 'Spicy Tamarind Tofu Pad Thai',
    description: 'Rice noodles wok-tossed with tamarind glaze, crispy pressed tofu, bean sprouts, crushed chili, and lime wedge.',
    restaurantId: 'rest_thai',
    restaurantName: 'Thai Orchid Street',
    price: 12.50,
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Thai',
    category: 'main',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    ingredients: ['rice noodles', 'tofu', 'tamarind', 'bean sprouts', 'peanuts', 'chili', 'lime'],
    spicyLevel: 2,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 540,
    proteinGrams: 22,
  },
  {
    id: 'meal_wild_mushroom_risotto',
    name: 'Wild Forest Mushroom Risotto',
    description: 'Creamy carnaroli rice simmered in white wine broth with sautéed cremini, porcini, thyme, and aged Parmigiano-Reggiano.',
    restaurantId: 'rest_roma',
    restaurantName: 'Roma Cucina',
    price: 16.00,
    imageUrl: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Italian',
    category: 'main',
    dietaryTags: ['vegetarian', 'gluten-free'],
    ingredients: ['carnaroli rice', 'cremini mushrooms', 'porcini mushrooms', 'parmesan', 'butter', 'thyme'],
    spicyLevel: 0,
    availableDays: ['tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['dinner'],
    active: true,
    calories: 610,
    proteinGrams: 16,
  },
  {
    id: 'meal_grilled_salmon_quinoa',
    name: 'Wild Salmon & Quinoa Superbowl',
    description: 'Pan-seared Atlantic salmon fillet atop organic tricolor quinoa, roasted sweet potatoes, kale, and lemon-dill vinaigrette.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 15.50,
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mediterranean',
    category: 'main',
    dietaryTags: ['gluten-free', 'dairy-free', 'high-protein', 'high-fibre', 'gut-friendly', 'weight-management'],
    ingredients: ['salmon', 'quinoa', 'kale', 'sweet potato', 'lemon', 'dill', 'olive oil'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 580,
    proteinGrams: 42,
  },
  {
    id: 'meal_margherita_pinsa',
    name: 'Artisan Pinsa Margherita',
    description: 'Roman sourdough crust topped with sweet San Marzano tomato sauce, fior di latte mozzarella, and fresh garden basil.',
    restaurantId: 'rest_roma',
    restaurantName: 'Roma Cucina',
    price: 11.50,
    imageUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Italian',
    category: 'main',
    dietaryTags: ['vegetarian'],
    ingredients: ['sourdough', 'san marzano tomato', 'fior di latte mozzarella', 'basil', 'extra virgin olive oil'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 570,
    proteinGrams: 24,
  },
  {
    id: 'meal_edamame_tofu_poke',
    name: 'Sesame Ginger Tofu Poké',
    description: 'Organic cubed tofu marinated in sesame tamari, avocado slices, shelled edamame, seaweed salad, and sushi rice.',
    restaurantId: 'rest_tokyo',
    restaurantName: 'Tokyo Bento Co.',
    price: 11.00,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Japanese',
    category: 'main',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'weight-management', 'high-fibre', 'gut-friendly'],
    ingredients: ['tofu', 'edamame', 'avocado', 'seaweed', 'sushi rice', 'sesame oil', 'tamari'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 490,
    proteinGrams: 21,
  },
  {
    id: 'meal_carne_asada_tacos',
    name: 'Carne Asada Street Tacos (3x)',
    description: 'Three warm corn tortillas with grilled marinated flank steak, white onion, cilantro, roasted salsa verde, and lime.',
    restaurantId: 'rest_fuego',
    restaurantName: 'El Fuego Taqueria',
    price: 13.50,
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mexican',
    category: 'main',
    dietaryTags: ['gluten-free', 'dairy-free', 'high-protein'],
    ingredients: ['beef', 'corn tortillas', 'salsa verde', 'white onion', 'cilantro', 'lime'],
    spicyLevel: 2,
    availableDays: ['tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 590,
    proteinGrams: 36,
  },

  // SIDES
  {
    id: 'side_spring_rolls',
    name: 'Crispy Veggie Spring Rolls (3x)',
    description: 'Hand-rolled crispy wrapper stuffed with glass noodles, cabbage, carrots, served with sweet chili dip.',
    restaurantId: 'rest_thai',
    restaurantName: 'Thai Orchid Street',
    price: 4.00,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Thai',
    category: 'side',
    dietaryTags: ['vegetarian', 'vegan', 'dairy-free'],
    ingredients: ['cabbage', 'carrots', 'glass noodles', 'flour wrap', 'sweet chili sauce'],
    spicyLevel: 1,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 220,
  },
  {
    id: 'side_edamame_sea_salt',
    name: 'Steamed Edamame with Maldon Salt',
    description: 'Young organic soy beans steamed in their pods with coarse Maldon sea salt flakes.',
    restaurantId: 'rest_tokyo',
    restaurantName: 'Tokyo Bento Co.',
    price: 4.00,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Japanese',
    category: 'side',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free', 'high-protein'],
    ingredients: ['edamame', 'sea salt'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 140,
    proteinGrams: 12,
  },
  {
    id: 'side_chips_guac',
    name: 'House Tortilla Chips & Guacamole',
    description: 'Freshly fried heirloom corn chips with chunky Hass avocado, lime, sea salt, and jalapeño.',
    restaurantId: 'rest_fuego',
    restaurantName: 'El Fuego Taqueria',
    price: 4.50,
    imageUrl: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mexican',
    category: 'side',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    ingredients: ['corn chips', 'avocado', 'lime', 'jalapeno', 'cilantro', 'onion'],
    spicyLevel: 1,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 320,
  },
  {
    id: 'side_garlic_herb_ciabatta',
    name: 'Tuscan Garlic Herb Ciabatta',
    description: 'Toasted rustic ciabatta brushed with garlic butter, rosemary, and sea salt.',
    restaurantId: 'rest_roma',
    restaurantName: 'Roma Cucina',
    price: 3.50,
    imageUrl: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Italian',
    category: 'side',
    dietaryTags: ['vegetarian'],
    ingredients: ['ciabatta flour', 'garlic', 'butter', 'rosemary', 'parsley'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 260,
  },
  {
    id: 'side_cucumber_tzatziki',
    name: 'Cucumber Radish Salad with Tzatziki',
    description: 'Crisp ribboned cucumbers, baby radishes, dill, and probiotic Greek yogurt tzatziki.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 4.00,
    imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mediterranean',
    category: 'side',
    dietaryTags: ['vegetarian', 'gluten-free'],
    ingredients: ['cucumber', 'radish', 'greek yogurt', 'dill', 'garlic', 'olive oil'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 120,
  },

  {
    id: 'side_vegetable_samosas',
    name: 'Vegetable Samosas (2 pcs)',
    description: 'Crispy flaky pastry stuffed with spiced potatoes, sweet green peas, and served with mint coriander chutney.',
    restaurantId: 'rest_gulati',
    restaurantName: "Gulati's Indian Kitchen",
    price: 4.00,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Indian',
    category: 'side',
    dietaryTags: ['vegetarian', 'vegan', 'halal'],
    ingredients: ['potatoes', 'peas', 'cumin', 'flour', 'spices'],
    spicyLevel: 1,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 210,
  },
  {
    id: 'side_mirchi_ka_salan',
    name: 'Mirchi Ka Salan',
    description: 'Authentic Hyderabadi slow-cooked green chili, sesame, peanut, and coconut curry sauce, the traditional accompaniment for Chicken Biryani.',
    restaurantId: 'rest_gulati',
    restaurantName: "Gulati's Indian Kitchen",
    price: 3.00,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Indian',
    category: 'side',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free', 'halal'],
    ingredients: ['green chili', 'peanuts', 'sesame seeds', 'coconut', 'tamarind', 'spices'],
    spicyLevel: 2,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 160,
  },
  {
    id: 'side_kachumber_salad',
    name: 'Fresh Kachumber & Raita Salad',
    description: 'Crisp diced cucumbers, red onions, plum tomatoes, fresh cilantro tossed with chaat masala and cooling spiced yogurt.',
    restaurantId: 'rest_gulati',
    restaurantName: "Gulati's Indian Kitchen",
    price: 2.50,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Indian',
    category: 'side',
    dietaryTags: ['vegetarian', 'gluten-free', 'gut-friendly', 'halal'],
    ingredients: ['cucumber', 'red onion', 'tomato', 'yogurt', 'mint', 'chaat masala'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 110,
  },


  // DRINKS
  {
    id: 'drink_mango_smoothie',
    name: 'Mango Smoothie',
    description: 'Fresh ripe mango puree whipped with chilled coconut water and Greek yoghurt with zero added sugar.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 6.00,
    imageUrl: 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Healthy',
    category: 'drink',
    dietaryTags: ['healthy', 'low-sugar', 'vegetarian'],
    ingredients: ['mango', 'coconut water', 'greek yoghurt'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 180,
    proteinGrams: 6,
  },
  {
    id: 'drink_mango_drink',
    name: 'Mango Drink (Alphonso Lassi)',
    description: 'Chilled artisanal yoghurt blended with sweet golden Alphonso mango nectar and cardamom.',
    restaurantId: 'rest_gulati',
    restaurantName: "Gulati's Indian Kitchen",
    price: 3.00,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Indian',
    category: 'drink',
    dietaryTags: ['vegetarian', 'gluten-free'],
    ingredients: ['mango', 'yoghurt', 'cardamom'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 180,
  },
  {
    id: 'drink_thai_iced_tea',
    name: 'Traditional Thai Iced Tea',
    description: 'Slow-brewed spiced Ceylon tea sweetened with condensed milk and poured over crushed ice.',
    restaurantId: 'rest_thai',
    restaurantName: 'Thai Orchid Street',
    price: 3.00,
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Thai',
    category: 'drink',
    dietaryTags: ['vegetarian', 'gluten-free'],
    ingredients: ['black tea', 'star anise', 'condensed milk', 'cardamom'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 190,
  },
  {
    id: 'drink_sparkling_hibiscus',
    name: 'Sparkling Hibiscus Berry Cooler',
    description: 'Cold-pressed hibiscus flower tea infused with fresh blackberry purée and sparkling mineral water.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 3.00,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mediterranean',
    category: 'drink',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    ingredients: ['hibiscus', 'blackberries', 'sparkling water', 'mint', 'agave'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 45,
  },
  {
    id: 'drink_roasted_green_tea',
    name: 'Iced Hojicha Roasted Green Tea',
    description: 'Fragrant roasted Japanese green tea brewed cold with zero sugar and a smooth nutty aroma.',
    restaurantId: 'rest_tokyo',
    restaurantName: 'Tokyo Bento Co.',
    price: 2.50,
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Japanese',
    category: 'drink',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    ingredients: ['roasted green tea leaves', 'spring water'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 0,
  },
  {
    id: 'drink_agua_fresca_lime',
    name: 'Cucumber Lime Agua Fresca',
    description: 'Refreshing blended cucumber juice with key lime, organic cane sugar, and fresh mint sprig.',
    restaurantId: 'rest_fuego',
    restaurantName: 'El Fuego Taqueria',
    price: 3.00,
    imageUrl: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Mexican',
    category: 'drink',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    ingredients: ['cucumber', 'lime', 'cane sugar', 'mint', 'water'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 85,
  },
  // DESSERTS
  {
    id: 'dessert_matcha_mochi',
    name: 'Matcha Gelato Mochi (2x)',
    description: 'Chilled soft mochi skin stuffed with authentic Kyoto matcha green tea gelato.',
    restaurantId: 'rest_tokyo',
    restaurantName: 'Tokyo Bento Co.',
    price: 3.50,
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Japanese',
    category: 'dessert',
    dietaryTags: ['vegetarian', 'gluten-free'],
    ingredients: ['glutinous rice', 'matcha', 'gelato', 'cane sugar'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 190,
  },
  {
    id: 'dessert_mango_sticky_rice',
    name: 'Mango Sticky Rice',
    description: 'Sweet coconut cream infused sticky rice with ripe golden mango slices and toasted sesame seeds.',
    restaurantId: 'rest_thai',
    restaurantName: 'Thai Orchid Street',
    price: 4.50,
    imageUrl: 'https://images.unsplash.com/photo-1621236378699-8597fee6a1ce?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Thai',
    category: 'dessert',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'],
    ingredients: ['sticky rice', 'mango', 'coconut cream', 'sesame'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 280,
  },
  {
    id: 'dessert_tiramisu_cup',
    name: 'Classic Tiramisu Cup',
    description: 'Espresso-soaked savoiardi ladyfingers layered with rich mascarpone cream and dusted with cocoa.',
    restaurantId: 'rest_roma',
    restaurantName: 'Roma Cucina',
    price: 4.00,
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Italian',
    category: 'dessert',
    dietaryTags: ['vegetarian'],
    ingredients: ['mascarpone', 'espresso', 'ladyfingers', 'cocoa'],
    spicyLevel: 0,
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 320,
  },
];

export const MOCK_USERS: Record<string, UserProfile> = {
  user_alex: {
    id: 'user_alex',
    name: 'Alex Chen',
    email: 'alex.chen@example.com',
    preferences: {
      favoriteCuisines: ['Thai', 'Japanese'],
      dislikedFoods: ['mushrooms'],
      dietaryPreferences: ['high-protein'],
      allergies: [], // Explicitly no allergies
      preferredPriceRange: { min: 10, max: 16 },
      spicyPreference: 'spicy',
      healthyPreference: false,
      favoriteRestaurants: ['Thai Orchid Street', 'Tokyo Bento Co.'],
      frequentProteins: ['chicken', 'beef'],
    },
  },
  user_sam: {
    id: 'user_sam',
    name: 'Sam Taylor',
    email: 'sam.taylor@example.com',
    preferences: {
      favoriteCuisines: ['Mediterranean', 'Italian'],
      dislikedFoods: ['mushrooms', 'bell peppers'],
      dietaryPreferences: ['vegetarian'],
      allergies: ['peanuts'], // Explicitly declared peanut allergy
      preferredPriceRange: { min: 9, max: 15 },
      spicyPreference: 'mild',
      healthyPreference: true,
      favoriteRestaurants: ['Verde Kitchen & Bowls', 'Roma Cucina'],
      frequentProteins: ['tofu', 'chickpeas'],
    },
  },
  user_jordan: {
    id: 'user_jordan',
    name: 'Jordan Lee',
    email: 'jordan.lee@example.com',
    preferences: {
      favoriteCuisines: ['Mexican', 'Korean'],
      dislikedFoods: [],
      dietaryPreferences: ['gluten-free'],
      allergies: [],
      preferredPriceRange: { min: 8, max: 14 },
      spicyPreference: 'spicy',
      healthyPreference: true,
      favoriteRestaurants: ['El Fuego Taqueria'],
      frequentProteins: ['chicken', 'beef'],
    },
  },
};

export const MOCK_ORDER_HISTORIES: Record<string, Order[]> = {
  user_alex: [
    {
      id: 'ord_alex_001',
      userId: 'user_alex',
      date: '2026-09-14',
      slot: 'dinner',
      items: [
        {
          mealId: 'meal_thai_basil_chicken',
          mealName: 'Thai Basil Chicken',
          price: 13.00,
          quantity: 1,
          restaurantName: 'Thai Orchid Street',
          category: 'main',
        },
        {
          mealId: 'drink_thai_iced_tea',
          mealName: 'Traditional Thai Iced Tea',
          price: 3.00,
          quantity: 1,
          restaurantName: 'Thai Orchid Street',
          category: 'drink',
        },
      ],
      subtotal: 16.00,
      deliveryFee: 2.99,
      tax: 1.44,
      total: 20.43,
      restaurantId: 'rest_thai',
      restaurantName: 'Thai Orchid Street',
      status: 'delivered',
      isUsual: true,
    },
    {
      id: 'ord_alex_002',
      userId: 'user_alex',
      date: '2026-09-11',
      slot: 'dinner',
      items: [
        {
          mealId: 'meal_spicy_katsu_chicken',
          mealName: 'Spicy Chicken Katsu Curry',
          price: 14.50,
          quantity: 1,
          restaurantName: 'Tokyo Bento Co.',
          category: 'main',
        },
      ],
      subtotal: 14.50,
      deliveryFee: 1.99,
      tax: 1.30,
      total: 17.79,
      restaurantId: 'rest_tokyo',
      restaurantName: 'Tokyo Bento Co.',
      status: 'delivered',
    },
    {
      id: 'ord_alex_003',
      userId: 'user_alex',
      date: '2026-09-08',
      slot: 'dinner',
      items: [
        {
          mealId: 'meal_thai_basil_chicken',
          mealName: 'Thai Basil Chicken',
          price: 13.00,
          quantity: 1,
          restaurantName: 'Thai Orchid Street',
          category: 'main',
        },
      ],
      subtotal: 13.00,
      deliveryFee: 2.99,
      tax: 1.17,
      total: 17.16,
      restaurantId: 'rest_thai',
      restaurantName: 'Thai Orchid Street',
      status: 'delivered',
      isUsual: true,
    },
  ],
  user_sam: [
    {
      id: 'ord_sam_001',
      userId: 'user_sam',
      date: '2026-09-12',
      slot: 'lunch',
      items: [
        {
          mealId: 'meal_falafel_power_bowl',
          mealName: 'Crispy Falafel & Tahini Bowl',
          price: 12.00,
          quantity: 1,
          restaurantName: 'Verde Kitchen & Bowls',
          category: 'main',
        },
        {
          mealId: 'drink_sparkling_hibiscus',
          mealName: 'Sparkling Hibiscus Berry Cooler',
          price: 3.00,
          quantity: 1,
          restaurantName: 'Verde Kitchen & Bowls',
          category: 'drink',
        },
      ],
      subtotal: 15.00,
      deliveryFee: 2.49,
      tax: 1.35,
      total: 18.84,
      restaurantId: 'rest_verde',
      restaurantName: 'Verde Kitchen & Bowls',
      status: 'delivered',
      isUsual: true,
    },
  ],
};
