import { Meal, Recommendation } from './types';

export const MOCK_MOBILE_MEALS: Meal[] = [
  {
    id: 'meal_thai_basil',
    name: 'Thai Basil Chicken',
    description: 'Wok-tossed minced chicken with fresh Thai holy basil, garlic, and birds eye chillies over jasmine rice.',
    restaurantId: 'rest_thai',
    restaurantName: 'Thai Orchid Street',
    price: 13.0,
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=400&q=80',
    cuisine: 'Thai',
    category: 'main',
    dietaryTags: ['High Protein', 'Spicy', 'Dairy-Free'],
    ingredients: ['Chicken', 'Thai Basil', 'Chilli', 'Garlic', 'Jasmine Rice'],
    spicyLevel: 2,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 520,
    proteinGrams: 36,
  },
  {
    id: 'meal_quinoa_bowl',
    name: 'Grilled Chicken Quinoa Bowl',
    description: 'Herb-marinated chicken breast over organic tri-color quinoa, roasted cherry tomatoes, cucumbers, and lemon-tahini drizzle.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 12.0,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=400&q=80',
    cuisine: 'Mediterranean',
    category: 'main',
    dietaryTags: ['Heart Healthy', 'High Protein', 'Low Sodium'],
    ingredients: ['Chicken Breast', 'Quinoa', 'Cucumber', 'Tomato', 'Lemon-Tahini'],
    spicyLevel: 0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 460,
    proteinGrams: 38,
  },
  {
    id: 'meal_salmon_bowl',
    name: 'Salmon Teriyaki & Brown Rice',
    description: 'Atlantic salmon fillet glazed with house teriyaki sauce, steamed broccoli, and toasted sesame brown rice.',
    restaurantId: 'rest_tokyo',
    restaurantName: 'Tokyo Bento Co.',
    price: 14.5,
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&q=80',
    cuisine: 'Japanese',
    category: 'main',
    dietaryTags: ['Omega-3', 'High Protein', 'Anti-Inflammatory'],
    ingredients: ['Atlantic Salmon', 'Brown Rice', 'Broccoli', 'Teriyaki', 'Sesame'],
    spicyLevel: 0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 510,
    proteinGrams: 34,
  },
  {
    id: 'meal_biryani',
    name: 'Hyderabadi Chicken Biryani',
    description: 'Fragrant basmati rice layered with spiced tender chicken, saffron, caramelised onions, and cooling mint raita.',
    restaurantId: 'rest_biryani',
    restaurantName: 'Deccan Spice Hub',
    price: 14.0,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80',
    cuisine: 'Indian',
    category: 'main',
    dietaryTags: ['Halal', 'High Protein', 'Aromatic'],
    ingredients: ['Chicken', 'Basmati Rice', 'Saffron', 'Mint', 'Yogurt'],
    spicyLevel: 2,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 620,
    proteinGrams: 32,
  },
  {
    id: 'meal_halloumi_bowl',
    name: 'Grilled Halloumi Green Bowl',
    description: 'Golden grilled halloumi cheese, roasted sweet potato, baby spinach, avocado, and pomegranate vinaigrette.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 12.5,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80',
    cuisine: 'Mediterranean',
    category: 'main',
    dietaryTags: ['Vegetarian', 'High Fibre', 'Diabetes Friendly'],
    ingredients: ['Halloumi', 'Sweet Potato', 'Spinach', 'Avocado', 'Pomegranate'],
    spicyLevel: 0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 440,
    proteinGrams: 22,
  },
  {
    id: 'meal_beef_rendang',
    name: 'Indonesian Beef Rendang',
    description: 'Slow-braised tender beef in coconut milk, lemongrass, galangal, kaffir lime, and aromatic spices with jasmine rice.',
    restaurantId: 'rest_nusantara',
    restaurantName: 'Nusantara Kitchen',
    price: 13.5,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=400&q=80',
    cuisine: 'Indonesian',
    category: 'main',
    dietaryTags: ['Halal', 'High Protein', 'Rich & Comforting'],
    ingredients: ['Beef', 'Coconut Milk', 'Lemongrass', 'Galangal', 'Chilli', 'Rice'],
    spicyLevel: 2,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 580,
    proteinGrams: 36,
  },
  {
    id: 'meal_jollof_chicken',
    name: 'Jollof Rice & Roasted Chicken',
    description: 'Smoky West African tomato and bell pepper rice served with spiced grilled chicken leg and fried sweet plantains.',
    restaurantId: 'rest_suya',
    restaurantName: 'Suya King African Kitchen',
    price: 12.0,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80',
    cuisine: 'African',
    category: 'main',
    dietaryTags: ['Halal', 'High Protein', 'Bold Flavours'],
    ingredients: ['Chicken', 'Jollof Rice', 'Habanero', 'Tomato', 'Plantain'],
    spicyLevel: 2,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 610,
    proteinGrams: 38,
  },
  {
    id: 'meal_lentil_curry',
    name: 'Creamy Coconut Lentil Curry',
    description: 'Slow-simmered golden lentils with turmeric, roasted cumin, coconut cream, wilted spinach, and warm flatbread.',
    restaurantId: 'rest_verde',
    restaurantName: 'Verde Kitchen & Bowls',
    price: 9.5,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80',
    cuisine: 'Indian',
    category: 'main',
    dietaryTags: ['Vegan', 'High Fibre', 'Gluten Free'],
    ingredients: ['Yellow Lentils', 'Coconut Milk', 'Spinach', 'Turmeric', 'Cumin'],
    spicyLevel: 1,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 390,
    proteinGrams: 18,
  },
  {
    id: 'meal_mango_lassi',
    name: 'Alphonso Mango Lassi',
    description: 'Chilled creamy yogurt drink blended with sweet Alphonso mango pulp and a touch of fragrant green cardamom.',
    restaurantId: 'rest_biryani',
    restaurantName: 'Deccan Spice Hub',
    price: 3.5,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=400&q=80',
    cuisine: 'Indian',
    category: 'drink',
    dietaryTags: ['Vegetarian', 'Cooling'],
    ingredients: ['Yogurt', 'Mango', 'Cardamom', 'Milk'],
    spicyLevel: 0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['lunch', 'dinner'],
    active: true,
    calories: 180,
    proteinGrams: 6,
  },
];

export function getMockRecommendations(query: string): Recommendation[] {
  const q = query.toLowerCase();
  let filtered = MOCK_MOBILE_MEALS;

  if (q.includes('spicy')) {
    filtered = MOCK_MOBILE_MEALS.filter((m) => m.spicyLevel > 0);
  } else if (q.includes('healthy') || q.includes('heart') || q.includes('protein')) {
    filtered = MOCK_MOBILE_MEALS.filter((m) =>
      m.dietaryTags.some((t) => t.toLowerCase().includes('healthy') || t.toLowerCase().includes('protein'))
    );
  }

  if (filtered.length === 0) filtered = MOCK_MOBILE_MEALS;

  return filtered.map((meal, index) => ({
    meal,
    score: 95 - index * 3,
    reasons: ['Matches your preferences', 'Top rated on Daily Drop'],
  }));
}
